# Generated by Django 3.0.2 on 2020-01-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commend_user', models.CharField(max_length=100, verbose_name='评论用户名')),
                ('commend_content', models.TextField(verbose_name='评论内容')),
                ('comment_datetime', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_post', models.CharField(max_length=200, verbose_name='收藏帖子标题')),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_user', models.CharField(max_length=100, verbose_name='关注着名称')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200, verbose_name='帖子标题')),
                ('image_url', models.CharField(max_length=255, verbose_name='图片保存路径')),
                ('thumbs_number', models.IntegerField(verbose_name='点赞数')),
                ('comment_number', models.IntegerField(verbose_name='评论数')),
                ('forwarding_number', models.IntegerField(verbose_name='转发量')),
                ('favorite_number', models.IntegerField(verbose_name='收藏数')),
                ('comment_id', models.IntegerField(verbose_name='评论id')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_message', models.IntegerField(default=1, verbose_name='是否短信提醒')),
                ('is_mail', models.IntegerField(default=1, verbose_name='是否邮箱提醒')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100, verbose_name='账号')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('nickname', models.CharField(max_length=100, verbose_name='昵称')),
                ('avatar', models.CharField(max_length=255, verbose_name='头像')),
                ('posts_number', models.IntegerField(verbose_name='发帖数')),
                ('fans', models.IntegerField(verbose_name='粉丝数')),
                ('follower_obj_number', models.IntegerField(verbose_name='关注人数')),
                ('level', models.IntegerField(verbose_name='等级')),
                ('individual_resume', models.CharField(max_length=255, verbose_name='个人简介')),
                ('mailbox', models.CharField(max_length=255, verbose_name='邮箱')),
                ('phone_number', models.IntegerField(verbose_name='手机号')),
                ('gender', models.IntegerField(verbose_name='性别')),
                ('is_disable', models.IntegerField(default=0, verbose_name='是否停用账号')),
                ('sub_id', models.IntegerField(verbose_name='订阅id')),
                ('post_id', models.IntegerField(verbose_name='帖子id')),
                ('follower_id', models.IntegerField(verbose_name='关注者id')),
                ('favorite_id', models.IntegerField(verbose_name='收藏id')),
            ],
        ),
    ]
