# Generated by Django 3.0.2 on 2020-01-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follower', '0003_auto_20200131_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='Not Set', max_length=10, verbose_name='性别'),
        ),
    ]
