# Generated by Django 3.0.2 on 2020-01-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follower', '0004_auto_20200131_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.CharField(max_length=20, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mailbox',
            field=models.CharField(max_length=20, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='手机号'),
        ),
    ]
