# Generated by Django 3.0.2 on 2020-01-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follower', '0006_auto_20200131_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mailbox',
            field=models.CharField(max_length=30, verbose_name='邮箱'),
        ),
    ]
