# Generated by Django 3.0.2 on 2020-02-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follower', '0007_auto_20200131_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=30, null=True, verbose_name='所在城市'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=30, verbose_name='手机号'),
        ),
    ]
