# Generated by Django 3.0.2 on 2020-02-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follower', '0009_auto_20200201_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mailbox',
            field=models.CharField(max_length=40, verbose_name='邮箱'),
        ),
    ]
